### ISSUE TITLE
Are negative samples required?

### ISSUE THREAD

**Issue by zishanahmed-tomtom** [facebookresearch/barlowtwins#10]
From the discussion session of the paper, 

> Another common point between the two
losses is that they both rely on batch statistics to measure
this variability. However, the INFO NCE objective maxi-
mizes the variability of the representation by maximizing
the pairwise distance between all pairs of samples, whereas
our method does so by decorrelating the components of the
representation vectors

This confuses me. 

My understanding is that the cross-correlation matrix only considers the decorrelation between a 2 augmentations of same image. As such, we don't need the negative samples present in the batch. Then how and why are the batch statistics considered in decorrelating the repr. vectors? Could you please explain if the negative sample are indeed considered in the loss function or not?

**Comment by jzbontar** [comment]
> My understanding is that the cross-correlation matrix only considers the decorrelation between a 2 augmentations of same image.

The empirical cross-correlation matrix is computed from all images in a batch. We cannot compute the cross-correlation matrix from (2 augmentations of) a single image. 

Consider C[i, j], the value in the i-th row and j-th column of the cross correlation matrix C. C[i, j] measures the correlation between the i-th and j-th feature of our 8192 dimensional representation. If you want to know how correlated the i-th and j-th feature are, you need to know the values of the i-th and j-th feature for many samples. We use a batch of samples to estimate this correlation.

I hope that makes it clear.

**Comment by jbattab** [comment]
I also holds a problem of understanding, there is no interaction between different samples in the batch.
for example in simclr then is s_ij, which is cosine distance between two samples in the batch. But in your work as I undeerstand from eq1,2 , each sample in the batch is only interects with itself . I'm missing something?

**Comment by jingli9111** [comment]
> I also holds a problem of understanding, there is no interaction between different samples in the batch.
> for example in simclr then is s_ij, which is cosine distance between two samples in the batch. But in your work as I undeerstand from eq1,2 , each sample in the batch is only interects with itself . I'm missing something?

In equation 2, when calculating correlation term, there are sums across batch dimension. So there are interaction among different samples. 
It's not like SimCLR to have pairwise interaction. It's an interaction through statistics among batch.
