### ISSUE TITLE
Bug Issues: loaded state dict has a different number of parameter groups

### ISSUE THREAD

**Issue by xinyu1205** [facebookresearch/barlowtwins#11]
Sorry to disturb you , I encountered a bug. I tried to use the model you released and use the classification task to verify it. When I load your released trained model using load_state_dict, it raises the following error:
`python evaluate.py /path/to/imagenet/ /path/to/checkpoint/resnet50.pth --lr-classifier 0.1`

`File "/home/amy/.local/lib/python3.7/site-packages/torch/optim/optimizer.py", line 118, in load_state_dict
    raise ValueError("loaded state dict has a different number of "
ValueError: loaded state dict has a different number of parameter groups
   `
However,when I try to use the model to do Semi-supervised Learning,It can run successfully.
`python evaluate.py /path/to/imagenet/ /path/to/checkpoint/resnet50.pth --weights finetune --train-perc 1 --epochs 20 --lr-backbone 0.002 --lr-classifier 0.5 --weight-decay 0`

**Comment by jzbontar** [comment]
Hello @xinyu1205,

thanks for reporting the bug. Can you try to add the `--checkpoint-dir` flag to `evaluate.py` like so:

```
python evaluate.py /path/to/imagenet/ /path/to/checkpoint/resnet50.pth --lr-classifier 0.1 --checkpoint-dir ./checkpoint2/
```

**Comment by xinyu1205** [comment]
Thank you for your quick reply,and your solution works. Best wishes!

**Comment by jzbontar** [comment]
I think I understand what went wrong. Both the semi-supervised and the linear evaluation use the same checkpoint directory (./checkpoint2/lincls). When you ran the linear evaluation it tried to load the checkpoint that was created by the semi-supervised training and crashed.

I'll update the README file.
