### ISSUE TITLE
Projector Network

### ISSUE THREAD

**Issue by Donny3000** [facebookresearch/barlowtwins#17]
Hello Barlow Twins Team!

First off, great work on the paper and providing a reference implementation of the concept! I have a couple of question regarding the projector network and it's usage. I know the paper discussed a little bit regarding the projector network, but I'm still not clear as to what its intention/purpose. Could someone provide more detail for its use and purpose? If there are other external resources that speak to this, I definitely wouldn't mind reading them. Also, after training the model do we use the projector network on further downstream tasks or do we just use the ResNet50 backbone? Thanks in advance for taking the time to address these concerns.

**Comment by jingli9111** [comment]
@Donny3000 
The projection head is proposed in the SimCLR paper: https://arxiv.org/pdf/2002.05709.pdf

For downstream tasks, the projection head is discarded. Only the ResNet50 backbone is used.

**Comment by Donny3000** [comment]
Thanks @jingli9111 for pointing me to the SlimCLR paper and the clarification on the projection head usage!
