### ISSUE TITLE
Typo in the architecture image

### ISSUE THREAD

**Issue by byildiz** [facebookresearch/barlowtwins#19]
In the architecture image, output names are not correctly written: YA -> ZB and YB -> ZA. They should be vice versa accourding to the paper:
> The two batches of distorted views YA and YB are then fed to a function fθ, typically a deep network with trainable parameters θ,producing batches of representations ZA and ZB respectively.

The same image is also used in the paper and there are the same typos, too.

**Comment by StphTphsn** [comment]
Good catch, will update, thanks!
