### ISSUE TITLE
DDP Wrapper in evaluate.py 

### ISSUE THREAD

**Issue by zhangdan8962** [facebookresearch/barlowtwins#22]
Hi,

I noticed that in evaluate.py, the resnet50 backbone was not wrapped in DDP. Can you maybe explain the reason behind it?

**Comment by jzbontar** [comment]
You are right, the resnet50 backbone should have been wrapped in DDP. Thanks for reporting the issue!

I updated evaluate.py so that the entire model is now wrapped in DDP. This change does not affect the accuracy results, only the runtime.
