### ISSUE TITLE
May I know how to implement BarlowTwins in Segmentation task? Thanks a lot.

### ISSUE THREAD

**Issue by semchan** [facebookresearch/barlowtwins#27]

**Comment by jzbontar** [comment]
One way to use Barlow twins in a Segmentation task would be to initialize the weights of the backbone ResNet50 using [Barlow twins](https://github.com/facebookresearch/barlowtwins#pretrained-model) and then train the Faster R-CNN or Mask R-CNN models from that initialization.

For more details, see section 3.2 and appendix C.2 of [our paper](https://arxiv.org/abs/2103.03230).
