### ISSUE TITLE
Issue loading checkpoint.pth file

### ISSUE THREAD

**Issue by davidrzs** [facebookresearch/barlowtwins#36]
Thank you very much for providing your code on GitHub. There is a problem when trying to load the checkpoint.pth file. If I load it using your latest code, it gives the error `AttributeError: Can't get attribute 'exclude_bias_and_norm' on <module '__main__'>`.

One can easily fix it by adding the following function to the file (not nested anywhere)
```python
def exclude_bias_and_norm(p):
    return p.ndim == 1
```
Commit `21149b45bda50e579f166a4e261f281924b7c208` from August 5th actually introduced this "bug" as you very likely included the original saved model but just changed the code.

It is a very minor thing, but I thought about pointing it out. The problem stems from how PyTorch serializes models - hence I hope by opening this issue other researchers having the same issue might see this easy solution.

Here you can find a Jupyter notebook detailing the problem and the fix:
[BugReport.zip](https://github.com/facebookresearch/barlowtwins/files/7575465/BugReport.zip)

**Comment by jingli9111** [comment]
Hi @davidrzs, thank you so much for pointing this out! We will update the checkpoint.
