### ISSUE TITLE
Augmentation Distribution

### ISSUE THREAD

**Issue by gabrieldernbach** [facebookresearch/barlowtwins#37]
Thanks for sharing!

I can see that you chose different distributions in transform and transform_prime, namely
```
GaussianBlur(p=0.1) vs (p=1.0)
Solarization(p=0.2) vs (p=0.0)
```
In the paper I could not find a clear motivation or ablation. Is there an intuition or experience you can share?
Kind regards.

**Comment by vladan-stojnic** [comment]
I think they were chosen to mimic the augmentations used in [BYOL paper](https://arxiv.org/pdf/2006.07733.pdf). Table 6 in the paper shows the parameters of the augmentations.
