### ISSUE TITLE
When using the own dataset, loss is around 10,000

### ISSUE THREAD

**Issue by yzakzero** [facebookresearch/barlowtwins#39]
Hi, Thank you for the code.  

How can I reduce loss to a more normal level?

Thanks！

**Comment by bip5** [comment]
I have similar level of loss although not sure if this is by design. Have you been able to match the expected results?

**Comment by yzakzero** [comment]
谢谢，收到！

**Comment by yzakzero** [comment]
谢谢，收到！

**Comment by LSnyd** [comment]
Hi @bip5 @yzakzero has anyone of you been able to lower the loss for other datasets? I am stuck at a loss of around 4000.

**Comment by yzakzero** [comment]
谢谢，收到！

**Comment by mug2mag** [comment]
I met the same problem that the loss is more than 400. Any suggestion or tip will be appreciated. @jingli9111

**Comment by yzakzero** [comment]
谢谢，收到！

**Comment by AricYang** [comment]
I'm having the same problem, I start with a loss of 3000 and down to 350 after 4 epochs of training. Please enlighten me if anyone got a clue.

**Comment by yzakzero** [comment]
谢谢，收到！
