### ISSUE TITLE
Shuffling BN and Single GPU

### ISSUE THREAD

**Issue by Mushtaqml** [facebookresearch/barlowtwins#4]
If we train it using single GPU, will we face the issue of information leakage due to BN as mentioned in the MoCo paper?

Thanks

**Comment by jzbontar** [comment]
Hi @Mushtaqml,

We don't use shuffle BN in Barlow Twins. We use [global BN](https://github.com/facebookresearch/barlowtwins/blob/52ffe5672cce03761036b401651cdf8459dcb72e/main.py#L89), instead. The code should, therefore, work the same (ignoring randomness and machine precision issues) regardless of whether you run it on a single GPU or multiple GPUs. 

I don't know if Barlow Twins would benefit from using shuffle BN. We haven't run that experiment yet. Shuffle BN is not used in SimCLR as well, for example.

**Comment by Mushtaqml** [comment]
Thank you for the explanation.
