### ISSUE TITLE
Applications on one-dimensional signal datasets

### ISSUE THREAD

**Issue by TQi-Yang** [facebookresearch/barlowtwins#46]
Hi, thank you for your work, it inspires me a lot.
I want to apply BT to my data set about one-dimensional pulse signals instead of images, the data length is 500, do you think it needs to be changed to 224? I did the following work: I changed the number of channels in resnet50 from 3 to 1, and conv2d to conv1d, but the output dimension is still 2048. Good results can be obtained with supervised networks, but the loss of self-supervised learning processes does not drop significantly, and the downstream classification tasks are not as good as supervised networks. mlp also raised the dimension to 8192, but that didn't work either.
What do you think might be the reason? Or can you give me some advice. Thanks again!

**Comment by jingli9111** [comment]
Hi @TQi-Yang 
Thanks for your interest in our work.

I suggest you don't change your data format. It's better just define your own backbone network. ResNet50 is designed for image.
For example: Your data input is [batch_size, 500]. Then have a few layer MLP (probably with residual connection) should be ok... no need to use a conv net I guess. I also don't think you need use output dimension 2048 and projection dimension 8192. Smaller ones should be enough for your case, e.g. 32 and 128.
It's important for you to find a new set of augmentations. The original ones are random-resized-cropping, color jitters, specifically designed for images. You probably should use 1d random-resized-cropping in your case.
Free feel to ask more questions!

Best,
Li

**Comment by TQi-Yang** [comment]
Hi @jingli9111 
Thanks for your quick reply, it helped me a lot! But there are some things I don't understand.

First of all, I know that ResNet50 is designed for image. But I am curious that the accuracy rate is stable at 80% in supervised learning,  I think it is quite good (8000 data for training, 1600 data for testing),  so I did not change the backbone network before you reply.
Secondly, can a few layer MLP extract features well for one-dimensional time series signals?
The last question, the data augmentation method I am using now is just adding different noises to open up the gap for comparison. I don't know much about data augmentation for one-dimensional signals, but 1d random-resized-cropping is very novel to me, and I am very willing to try it. For data with a length of 500, what are the requirements for the length after cropping? How much will it be set according to your experience?

I am very happy to be able to communicate with you, thank you!

**Comment by jingli9111** [comment]
Hi @TQi-Yang,

All joint-embedding methods rely on augmentations, .e.g random-resized-crop, color-jittering, gaussian blur. 
Our method, SimCLR, BYOL and many other similar ones all rely on this. 
You can check SimCLR paper for more detail on how these augmentations are designed. 
In principle, augmentations are designed to prevent corresponding trivial solutions, e.g., color jittering prevents the network to use color histogram as a feature. Adding noise usually does not help in my experience.


Also, looks like this discussion is not related to the repo here.
I will close this issue. Feel free to send me emails if you want to continue this discussion.

Best,
Li

**Comment by TQi-Yang** [comment]
Hi @jingli9111 

OK, these helped me a lot. Thanks again for your patience in answering.
