### ISSUE TITLE
Error in saving resnet50.pth

### ISSUE THREAD

**Issue by gurdeepmaurya** [facebookresearch/barlowtwins#51]
https://github.com/facebookresearch/barlowtwins/blob/8e8d284ca0bc02f88b92328e53f9b901e86b4a3c/main.py#L151

Hi,

Since module is not a layer in BarlowTwin's definition, L151 should be
` torch.save(model.backbone.state_dict(),
                   args.checkpoint_dir / 'resnet50.pth')`

Regards

**Comment by jingli9111** [comment]
@gurdeepmaurya 
please read https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-torch-nn-dataparallel-models

**Comment by gurdeepmaurya** [comment]
> @gurdeepmaurya please read https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-torch-nn-dataparallel-models

Thanks for the clarification. I converted the code for 1 GPU (removed Datasistributed parallel) and was getting errors on these lines. I suppose in the normal model ( i.e. w/o DDP) we don't need `model.module`.

Could you please clarify one more thing? What was the batch size for figure 4 (Projector dimensionality ablation study) in your paper and also if you guys increased the batch size for different projector dimensions?

Thanks and Regards
